import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    width: "100%",
    height: "10%",  
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  backButton: {
    padding: 10,
    backgroundColor: "#4E598C",
    borderRadius: 5,
  },
  Text: {
    color: "#1D3557",
    fontSize: 16,
    fontWeight: "bold",
    position: "absolute",
    left: "40%",
    transform: [{ translateX: -50 }],
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  menuText: {
    fontSize: 16,
    padding: 10,
  },
  activityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    paddingHorizontal: 15,
  },
  timeBadge: {
    backgroundColor: "#6A5ACD", 
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginRight: 10,
  },
  timeText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  activityText: {
    color: "#1D3557",
    fontSize: 16,
  },
  separator: {
    height: 1,
    backgroundColor: "#D3D3D3",
    marginVertical: 8,
    width: "90%",
    alignSelf: "center",
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#4E598C",
    padding: 15,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: "40%",
    height: "60%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
  },
  priorityButton: {
    backgroundColor: "#1D3557",
    borderRadius: 20,
    padding: 10,
  },
  priorityButtonText: {
    color: "white",
    fontSize: 16,
  },
  input: {
    height: 250,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    width: "100%",
    marginTop: 30,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  saveButton: {
    backgroundColor: "#1D3557",
    borderRadius: 20,
    padding: 10,
    flex: 1,
    marginLeft: 5,
  },
  saveButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#4E598C",
    borderRadius: 20,
    padding: 10,
    flex: 1,
    marginRight: 5,
  },
  cancelButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
});

export default styles;