import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    width: "100%",
    height: "10%",  
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  backButton: {
    padding: 10,
    backgroundColor: "#00A8CC",
    borderRadius: 5,
  },
  Text: {
    color: "#1D3557",
    fontSize: 16,
    fontWeight: "bold",
    position: "absolute",
    left: "40%",
    transform: [{ translateX: -50 }],
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  menuText: {
    fontSize: 16,
    padding: 10,
  },
  activityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    paddingHorizontal: 15,
  },
  timeBadge: {
    backgroundColor: "#6A5ACD", 
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginRight: 10,
  },
  emptyText: {
    textAlign: "center",
    fontSize: 16,
    color: "#888",
    marginTop: 20,
  },
  
  timeText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  activityText: {
    color: "#1D3557",
    fontSize: 16,
  },

  separator: {
    height: 1,
    backgroundColor: "#D3D3D3",
    marginVertical: 8,
    width: "95%",
    alignSelf: "center",
  },
  
  addButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#00A8CC",
    padding: 15,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1D3557",
  },
  modalTitle2:{
    fontSize: 16,
    color: "#1D3557",
    alignItems: "center",
  },
  hora:{
    marginTop: 11,
    backgroundColor: "#EAEDED",
    borderRadius: 20,
    padding: 10,
    alignItems: "stretch",
    shadowColor: "#000",
    shadowRadius: 4,
    elevation: 5,
    width: "60%",
  },
  priorityButton: {
    backgroundColor: "#1D3557",
    borderRadius: 20,
    padding: 10,
  },
  priorityButtonText: {
    color: "white",
    fontSize: 16,
  },
  input: {
    height: 150,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    width: "100%",
    marginTop: 30,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  saveButton: {
    backgroundColor: "#00A8CC",
    borderRadius: 20,
    padding: 10,
    flex: 1,
    marginLeft: 5,
  },
  saveButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#1D3557",
    borderRadius: 20,
    padding: 10,
    flex: 1,
    marginRight: 5,
  },
  cancelButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  timePickerButton: {
    backgroundColor: "#E9C46A",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginVertical: 10,
  },
  
  timePickerText: {
    color: "#264653",
    fontSize: 16,
    fontWeight: "bold",
  },

  prioridadAlta: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "red",
    position: "absolute",
    right: 10,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  switchLabel: {
    fontSize: 16,
    color: "#1D3557",
  },
  //editar eliminar
  selectedActivity: {
    backgroundColor: "#E0E0E0",
  },
  actionButtonsContainer: {
    flexDirection: "column", 
    justifyContent: "space-between",
    padding: 20,
  },
  deleteButton: {
    backgroundColor: "#FF0000",
    padding: 10, 
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10, 
    width: "50%",
  },
  deleteButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  editButton: {
    backgroundColor: "#007BFF",
    padding: 10, 
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10, 
    width: "50%",
  },
  editButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  cancelButton1: {
    backgroundColor: "#1D3557",
    padding: 10, 
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    width: "50%",
  },
  cancelButtonText1: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  selectionCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1D3557",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  innerCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#1D3557",
  },
  //busqueda
  searchInput: {
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginRight: 10,
    flex: 1,
  },
});

export default styles;