import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    width: "100%",
    height: 60,  
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1D3557",
    paddingHorizontal: 15,
    paddingVertical: 5,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  
  Text: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    position: "absolute",
    left: "50%",
    transform: [{ translateX: -50 }],
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  menuText: {
    fontSize: 16,
    padding: 10,
  },
  activityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderRadius: 12,
    marginHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  timeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 15,
    minWidth: 85,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  emptyText: {
    textAlign: "center",
    fontSize: 16,
    color: "#888",
    marginTop: 40,
    fontStyle: "italic",
  },
  
  timeText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  activityText: {
    color: "#1D3557",
    fontSize: 16,
    flex: 1,
    lineHeight: 22,
  },
  
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#1D3557",
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalView: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1D3557",
    textAlign: "center",
  },
  modalTitle2:{
    fontSize: 16,
    color: "#1D3557",
    textAlign: "center",
  },
  hora:{
    marginTop: 15,
    backgroundColor: "#F5F7FA",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    width: "100%",
    borderWidth: 1,
    borderColor: "#E6EAF0",
  },
  priorityButton: {
    backgroundColor: "#1D3557",
    borderRadius: 20,
    padding: 10,
  },
  priorityButtonText: {
    color: "white",
    fontSize: 16,
  },
  input: {
    height: 120,
    borderColor: "#E6EAF0",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 15,
    width: "100%",
    marginTop: 25,
    backgroundColor: "#F5F7FA",
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 25,
  },
  saveButton: {
    backgroundColor: "#00A8CC",
    borderRadius: 12,
    padding: 14,
    flex: 1,
    marginLeft: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  saveButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  cancelButton: {
    backgroundColor: "#1D3557",
    borderRadius: 12,
    padding: 14,
    flex: 1,
    marginRight: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  cancelButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  timePickerButton: {
    backgroundColor: "#E9C46A",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginVertical: 10,
  },
  
  timePickerText: {
    color: "#264653",
    fontSize: 16,
    fontWeight: "bold",
  },

  prioridadAlta: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#FF3B30",
    position: "absolute",
    right: 15,
    shadowColor: "#FF3B30",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 3,
  },
  switchContainer: {
    alignItems: "flex-start", 
    width: "100%",
    marginTop: 18,
    backgroundColor: "#F5F7FA",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6EAF0",
  },
  switchLabel: {
    fontSize: 16,
    color: "#1D3557",
    fontWeight: "500",
    marginBottom: 10,
  },
  switch: {
    alignSelf: "center",
  },
  selectedActivity: {
    backgroundColor: "#E8F4F8",
    borderWidth: 1,
    borderColor: "#00A8CC",
  },
  actionButtonsContainer: {
    flexDirection: "column", 
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  deleteButton: {
    backgroundColor: "#FF3B30",
    padding: 12, 
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12, 
    width: "50%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  deleteButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  editButton: {
    backgroundColor: "#007BFF",
    padding: 12, 
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12, 
    width: "50%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  editButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  cancelButton1: {
    backgroundColor: "#1D3557",
    padding: 12, 
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "50%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  cancelButtonText1: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  selectionCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#00A8CC",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: "white",
  },
  innerCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#00A8CC",
  },
  searchInput: {
    height: 40,
    borderColor: "#E6EAF0",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    marginRight: 10,
    flex: 1,
    backgroundColor: "#F5F7FA",
  },

  scrollContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  taskCardCompleted: {
    opacity: 0.7,
    backgroundColor: "#F8F8F8",
  },
});

export default styles;